### ISSUE TITLE
synopsysctl v1 not backwards compatible with synopsys v2020 blackduck installations

### ISSUE THREAD

**Issue by alexclineargo** [blackducksoftware/synopsysctl#94]
**What happened**:
While trying to administer a blackduck installation created in Aug 2019 the current version of synosysctl throws an error and is able to get the existing blackduck installation.
```
$ synopsysctl-v1.0.3 get blackduck blackduck -n blackduck-prod
ERRO[0001] synopsyctl failed: failed to get Blackduck values: unable to find release 'blackduck' in namespace 'blackduck-prod'
```

**What you expected to happen**:
I expected the new version to be backwards compatible with existing blackduck clusters.
```
$ synopsysctl-v2020.3.0 get blackduck blackduck -n blackduck-prod
NAME        AGE
blackduck   307d
```

**How to reproduce it (as minimally and precisely as possible)**:
See the above output from both versions of synopsysctl.

**Screenshots/additional context**:
I was able to retrieve the old version of synopsysctl from this archived repo: https://github.com/blackducksoftware/synopsys-operator/releases/tag/2020.3.0

**Environment:**
Kubernetes version 1.14 hosted in AWS EKS:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-21T01:25:41Z", GoVersion:"go1.13.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by msenmurugan** [comment]
@alexclineargo it's an expected behavior. From synopsysctl 1.0.0 or later, we have moved out of Synopsys Operator, so the synopsysctl utility don't support both operator based and synopsysctl based deployment at the same time. If you want to administer Operator based Black Duck deployment, then you need to use pre synopsysctl 1.0.0. It's already covered as part of FAQ

https://synopsys.atlassian.net/wiki/spaces/BDLM/pages/488243643/Frequently+Asked+Questions#If-you-have-multiple-Black-Duck-instances-deployed-with-Synopsys-Operator-and-you-only-want-to-update-one-instance-with-synopsysctl-1.0.0-or-later%3F

**Comment by alexclineargo** [comment]
Interesting. I didn't come across that wiki article while troubleshooting yesterday. This issue can serve as another documentation resource for others who might have this issue.

Closing.
